HotelsReservation.WebUI/Models/DestinationModel.cs
namespace HotelsReservation.WebUI.Models
{
	public class DestinationModel
	{
        public bool status { get; set; }
        public string message { get; set; }
        public long timestamp { get; set; }
        public List<Destination> data { get; set; }


        public class Destination
		{
            public string dest_id { get; set; }
            public string search_type { get; set; }
            public string type { get; set; }
            public string region { get; set; }
            public int? hotels { get; set; }
            public string roundtrip { get; set; }
            public string dest_type { get; set; }
            public string lc { get; set; }
            public double? longitude { get; set; }
            public double? latitude { get; set; }
            public string label { get; set; }
            public string city_name { get; set; }
            public string country { get; set; }
            public string image_url { get; set; }
            public string cci { get; set; }
            public int? nr_hotels { get; set; }
            public string name { get; set; }
            public object city_ufi { get; set; }
        }

	}
}

HotelsReservation.WebUI/Models/ErrorViewModel.cs
namespace HotelsReservation.WebUI.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

HotelsReservation.WebUI/Models/HotelsViewModel.cs
namespace HotelsReservation.WebUI.Models
{
    public class HotelsViewModel
    {
        public bool status { get; set; }
        public string message { get; set; }
        public long timestamp { get; set; }

        public Data data { get; set; } 

        public class Data
        {
            public List<Hotel> hotels { get; set; } 
        }

        public class Hotel
        {
            public string hotel_id { get; set; }
            public string accessibilityLabel { get; set; }
            public Property property { get; set; }
        }

        public class Property
        {
            public string[] photoUrls { get; set; }
            public string name { get; set; }
            public string currency { get; set; }
            public string reviewScore { get; set; }
            public string reviewScoreWord { get; set; }
            public PriceBreakdown priceBreakdown { get; set; }
        }

        public class PriceBreakdown
        {
            public GrossPrice grossPrice { get; set; }
            public StrikeThroughPrice strikethroughPrice { get; set; }
        }

        public class GrossPrice
        {
            public double value { get; set; }
            public string currency { get; set; }
            
        }

        public class StrikeThroughPrice
        {
            public double value { get; set; }
            public string currency { get; set; }
        }
    }

}

HotelsReservation.WebUI/Controllers/DefaultController.cs
using HotelsReservation.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using Newtonsoft.Json;

namespace HotelsReservation.WebUI.Controllers
{
    public class DefaultController : Controller
    {
        private readonly string _apiKey = "29810ee6aamsh28a42ebad6975e1p1ce7ebjsn835bad515f4a";
        private readonly string _apiHost = "booking-com15.p.rapidapi.com";
        private readonly HttpClient _httpClient;

        public DefaultController()
        {
            _httpClient = new HttpClient();
        }

        public IActionResult Index() => View();

        public IActionResult HotelList() => View();

        [HttpPost]
        public async Task<IActionResult> HotelList(string city, string arrival_date, string departure_date, string adults)
        {
            try
            {
                var destinations = await GetHotelDestinations(city.ToLower());
                var selectedDestination = GetRandomDestination(destinations);
                var hotels = await SearchHotels(selectedDestination, arrival_date, departure_date, adults);
                return View(hotels);
            }
            catch (Exception ex)
            {
                // Log error
                return View("Error");
            }
        }

        private DestinationModel.Destination GetRandomDestination(List<DestinationModel.Destination> destinations)
        {
            var random = new Random();
            var randomIndex = random.Next(0, destinations.Count);
            return destinations[randomIndex];
        }

        private async Task<HotelsViewModel.Data> SearchHotels(DestinationModel.Destination destination, string arrivalDate, string departureDate, string adults)
        {
            var request = CreateApiRequest(
                $"https://booking-com15.p.rapidapi.com/api/v1/hotels/searchHotels?dest_id={destination.dest_id}" +
                $"&search_type={destination.search_type}&arrival_date={arrivalDate}&departure_date={departureDate}" +
                $"&adults={adults}&children_age=0%2C17&room_qty=1&page_number=1&units=metric&temperature_unit=c" +
                $"&languagecode=en-us&currency_code=USD"
            );

            using var response = await _httpClient.SendAsync(request);
            response.EnsureSuccessStatusCode();
            var content = await response.Content.ReadAsStringAsync();
            var result = JsonConvert.DeserializeObject<HotelsViewModel>(content);
            return result.data;
        }

        [HttpGet]
        public async Task<List<DestinationModel.Destination>> GetHotelDestinations(string query)
        {
            var request = CreateApiRequest(
                $"https://booking-com15.p.rapidapi.com/api/v1/hotels/searchDestination?query={query}"
            );

            using var response = await _httpClient.SendAsync(request);
            response.EnsureSuccessStatusCode();
            var content = await response.Content.ReadAsStringAsync();
            var result = JsonConvert.DeserializeObject<DestinationModel>(content);
            return result.data;
        }

        private HttpRequestMessage CreateApiRequest(string uri)
        {
            return new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri(uri),
                Headers =
                {
                    { "x-rapidapi-key", _apiKey },
                    { "x-rapidapi-host", _apiHost },
                }
            };
        }
    }
}

HotelsReservation.WebUI/Controllers/HomeController.cs
using HotelsReservation.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HotelsReservation.WebUI.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

HotelsReservation.WebUI/Views/Default/HotelList.cshtml
@model HotelsReservation.WebUI.Models.HotelsViewModel.Data

@{
    Layout = "_MainLayout";
}

<!-- ##### Breadcumb Area Start ##### -->
<section class="breadcumb-area bg-img d-flex align-items-center justify-content-center" style="background-image: url(/palatin-gh-pages/img/bg-img/bg-6.jpg);">
    <div class="bradcumbContent">
        <h2>Oteller</h2>
    </div>
</section>
<!-- ##### Breadcumb Area End ##### -->

<!-- ##### Book Now Area Start ##### -->
<div class="book-now-area">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-12">
                <div class="book-now-form">
                    <form asp-controller="Default" asp-action="HotelList" method="post">
                        <!-- Form Group -->
                        <div class="form-group">
                            <label for="city">City</label>
                            <input type="text" class="form-control" name="city" id="city" placeholder="Enter city name">
                        </div>

                        <!-- Form Group -->
                        <div class="form-group">
                            <label for="checkin">Check In</label>
                            <input type="date" class="form-control" name="checkIn" id="checkin">
                        </div>

                        <!-- Form Group -->
                        <div class="form-group">
                            <label for="checkout">Check Out</label>
                            <input type="date" class="form-control" name="checkOut" id="checkout">
                        </div>

                        <!-- Form Group -->
                        <div class="form-group">
                            <label for="adults">Adults</label>
                            <div class="number-spinner">
                                <button type="button" class="spinner-btn minus">-</button>
                                <input type="number" class="form-control" name="adultCount" id="adults" value="1" min="1" max="10">
                                <button type="button" class="spinner-btn plus">+</button>
                            </div>
                        </div>

                        <!-- Button -->
                        <button type="submit" class="btn palatin-btn">Otel Ara</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ##### Book Now Area End ##### -->

<!-- ##### Rooms Area Start ##### -->
<section class="rooms-area section-padding-0-100">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-6">
                <div class="section-heading text-center">
                    <div class="line-"></div>
                    <h2>Otel Listesi</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris sceleri sque, at rutrum nulla dictum. Ut ac ligula sapien.</p>
                </div>
            </div>
        </div>

        <div class="row">
            @foreach (var item in Model.hotels)
            {
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="single-rooms-area wow fadeInUp" data-wow-delay="100ms">
                        <!-- Thumbnail -->
                        <div class="bg-thumbnail bg-img" style="background-image: url(@item.property.photoUrls[0]);"></div>
                        <!-- Price -->
                        <p class="price-from">Fiyat: @item.property.priceBreakdown.grossPrice.value.ToString("F2") @item.property.priceBreakdown.grossPrice.currency  </p>
                        <!-- Rooms Text -->
                        <div class="rooms-text">
                            <div class="line"></div>
                            <h4>@item.property.name</h4>
                            <p>@item.accessibilityLabel.Substring(0,100)...</p>
                            <p>Otel Puanı: @item.property.reviewScore</p>
                           
                        </div>
                        <!-- Book Room -->
                        <a href="#" class="book-room-btn btn palatin-btn">Oteller Bak</a>
                    </div>
                </div>
            }
        </div>
    </div>
</section>
<!-- ##### Rooms Area End ##### -->

HotelsReservation.WebUI/Views/Default/Index.cshtml
@{
    Layout = "_MainLayout";
}

<!-- ##### Hero Area Start ##### -->
@await Component.InvokeAsync("_HeroSectionComponentPartial")
<!-- ##### Hero Area End ##### -->

<!-- ##### Book Now Area Start ##### -->
<div class="book-now-area">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-12">
                <div class="book-now-form">
                    <form asp-controller="Default" asp-action="HotelList" method="post">
                        <!-- Form Group -->
                        <div class="form-group">
                            <label for="city">City</label>
                            <input type="text" class="form-control" name="city" id="city" placeholder="Enter city name">
                        </div>

                        <!-- Form Group -->
                        <div class="form-group">
                            <label for="checkin">Check In</label>
                            <input type="date" class="form-control" name="arrival_date" id="checkin">
                        </div>

                        <!-- Form Group -->
                        <div class="form-group">
                            <label for="checkout">Check Out</label>
                            <input type="date" class="form-control" name="departure_date" id="checkout">
                        </div>

                        <!-- Form Group -->
                        <div class="form-group">
                            <label for="adults">Adults</label>
                            <div class="number-spinner">
                                <button type="button" class="spinner-btn minus">-</button>
                                <input type="number" class="form-control" name="adults" id="adults" value="1" min="1" max="10">
                                <button type="button" class="spinner-btn plus">+</button>
                            </div>
                        </div>

                   

                        <!-- Button -->
                        <button type="submit" class="btn palatin-btn">Otel Ara</button>
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>
<!-- ##### Book Now Area End ##### -->

<!-- ##### About Us Area Start ##### -->
@await Component.InvokeAsync("_AboutUsComponentPartial")
<!-- ##### About Us Area End ##### -->

<!-- ##### Pool Area Start ##### -->
@await Component.InvokeAsync("_PoolAreaComponentPartial")
<!-- ##### Pool Area End ##### -->

@section Scripts {
    <script>
        $(document).ready(function() {
            // Plus button click event
            $('.spinner-btn.plus').click(function() {
                var input = $(this).siblings('input[type="number"]');
                var currentValue = parseInt(input.val());
                if (currentValue < parseInt(input.attr('max'))) {
                    input.val(currentValue + 1);
                }
            });

            // Minus button click event
            $('.spinner-btn.minus').click(function() {
                var input = $(this).siblings('input[type="number"]');
                var currentValue = parseInt(input.val());
                if (currentValue > parseInt(input.attr('min'))) {
                    input.val(currentValue - 1);
                }
            });
        });
    </script>
}

HotelsReservation.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HotelsReservation.WebUI/Views/Shared/Components/_AboutUsComponentPartial/Default.cshtml
<section class="about-us-area">
        <div class="container">
            <div class="row align-items-center">

                <div class="col-12 col-lg-6">
                    <div class="about-text text-center mb-100">
                        <div class="section-heading text-center">
                            <div class="line-"></div>
                            <h2>A place to remember</h2>
                        </div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris sceleri sque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris sceleri sque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>
                        <div class="about-key-text">
                            <h6><span class="fa fa-check"></span> Donec malesuada lorem maximus mauris sceleri</h6>
                            <h6><span class="fa fa-check"></span> Malesuada lorem maximus mauris sceleri</h6>
                        </div>
                        <a href="#" class="btn palatin-btn mt-50">Read More</a>
                    </div>
                </div>

                <div class="col-12 col-lg-6">
                    <div class="about-thumbnail homepage mb-100">
                        <!-- First Img -->
                        <div class="first-img wow fadeInUp" data-wow-delay="100ms">
                            <img src="/palatin-gh-pages/img/bg-img/5.jpg" alt="">
                        </div>
                        <!-- Second Img -->
                        <div class="second-img wow fadeInUp" data-wow-delay="300ms">
                            <img src="/palatin-gh-pages/img/bg-img/6.jpg" alt="">
                        </div>
                        <!-- Third Img-->
                        <div class="third-img wow fadeInUp" data-wow-delay="500ms">
                            <img src="/palatin-gh-pages/img/bg-img/7.jpg" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

HotelsReservation.WebUI/Views/Shared/Components/_FooterComponentPartial/Default.cshtml
    <!-- ##### Footer Area Start ##### -->
    <footer class="footer-area">
        <div class="container">
            <div class="row">

                <!-- Footer Widget Area -->
                <div class="col-12 col-lg-5">
                    <div class="footer-widget-area mt-50">
                        <a href="#" class="d-block mb-5"><img src="/palatin-gh-pages/img/core-img/logo.png" alt=""></a>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris sceleri sque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus. </p>
                    </div>
                </div>

                <!-- Footer Widget Area -->
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="footer-widget-area mt-50">
                        <h6 class="widget-title mb-5">Find us on the map</h6>
                        <img src="/palatin-gh-pages/img/bg-img/footer-map.png" alt="">
                    </div>
                </div>

                <!-- Footer Widget Area -->
                <div class="col-12 col-md-6 col-lg-3">
                    <div class="footer-widget-area mt-50">
                        <h6 class="widget-title mb-5">Subscribe to our newsletter</h6>
                        <form action="#" method="post" class="subscribe-form">
                            <input type="email" name="subscribe-email" id="subscribeemail" placeholder="Your E-mail">
                            <button type="submit">Subscribe</button>
                        </form>
                    </div>
                </div>

                <!-- Copywrite Text -->
                <div class="col-12">
                    <div class="copywrite-text mt-30">
                        <p><a href="#"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Emre Kuş</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->

HotelsReservation.WebUI/Views/Shared/Components/_HeaderComponentPartial/Default.cshtml
  <header class="header-area">
        <!-- Navbar Area -->
        <div class="palatin-main-menu">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    <!-- Menu -->
                    <nav class="classy-navbar justify-content-between" id="palatinNav">

                        <!-- Nav brand -->
                        <a href="/palatin-gh-pages/index.html" class="nav-brand"><img src="/palatin-gh-pages/img/core-img/logo.png" alt=""></a>

                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>

                        <!-- Menu -->
                        <div class="classy-menu">

                            <!-- close btn -->
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>

                            <!-- Nav Start -->
                            <div class="classynav">
                                <ul>
                                    <li class="active"><a href="/Default/Index">Ana Sayfa</a></li>
                                    <li><a href="#">Hakkımızda</a></li>
                                    <li><a href="#">Sayfalar</a>
                                    </li>
                                  
                                    <li><a href="#">Hizmetler</a></li>
                                    <li><a href="#">İletişim</a></li>
                                </ul>

                                <!-- Button -->
                                <div class="menu-btn">
                                    <a href="#" class="btn palatin-btn">Rezervasyon Yap</a>
                                </div>

                            </div>
                            <!-- Nav End -->
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>

HotelsReservation.WebUI/Views/Shared/Components/_HeroSectionComponentPartial/Default.cshtml
  <section class="hero-area">
        <div class="hero-slides owl-carousel">

            <!-- Single Hero Slide -->
            <div class="single-hero-slide d-flex align-items-center justify-content-center">
                <!-- Slide Img -->
                <div class="slide-img bg-img" style="background-image: url(/palatin-gh-pages/img/bg-img/bg-1.jpg);"></div>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-12 col-lg-9">
                            <!-- Slide Content -->
                            <div class="hero-slides-content" data-animation="fadeInUp" data-delay="100ms">
                                <div class="line" data-animation="fadeInUp" data-delay="300ms"></div>
                                <h2 data-animation="fadeInUp" data-delay="500ms">The Vacation Heaven</h2>
                                <p data-animation="fadeInUp" data-delay="700ms">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris sceleri sque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>
                                <a href="#" class="btn palatin-btn mt-50" data-animation="fadeInUp" data-delay="900ms">Read More</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Single Hero Slide -->
            <div class="single-hero-slide d-flex align-items-center justify-content-center">
                <!-- Slide Img -->
                <div class="slide-img bg-img" style="background-image: url(/palatin-gh-pages/img/bg-img/bg-2.jpg);"></div>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-12 col-lg-9">
                            <!-- Slide Content -->
                            <div class="hero-slides-content" data-animation="fadeInUp" data-delay="100ms">
                                <div class="line" data-animation="fadeInUp" data-delay="300ms"></div>
                                <h2 data-animation="fadeInUp" data-delay="500ms">A place to remember</h2>
                                <p data-animation="fadeInUp" data-delay="700ms">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris sceleri sque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>
                                <a href="#" class="btn palatin-btn mt-50" data-animation="fadeInUp" data-delay="900ms">Read More</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Single Hero Slide -->
            <div class="single-hero-slide d-flex align-items-center justify-content-center">
                <!-- Slide Img -->
                <div class="slide-img bg-img" style="background-image: url(/palatin-gh-pages/img/bg-img/bg-3.jpg);"></div>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-12 col-lg-9">
                            <!-- Slide Content -->
                            <div class="hero-slides-content" data-animation="fadeInUp" data-delay="100ms">
                                <div class="line" data-animation="fadeInUp" data-delay="300ms"></div>
                                <h2 data-animation="fadeInUp" data-delay="500ms">Enjoy your life</h2>
                                <p data-animation="fadeInUp" data-delay="700ms">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris sceleri sque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>
                                <a href="#" class="btn palatin-btn mt-50" data-animation="fadeInUp" data-delay="900ms">Read More</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>

HotelsReservation.WebUI/Views/Shared/Components/_PoolAreaComponentPartial/Default.cshtml
  <section class="pool-area section-padding-100 bg-img bg-fixed" style="background-image: url(/palatin-gh-pages/img/bg-img/4.png);">
        <div class="container">
            <div class="row justify-content-end">
                <div class="col-12 col-lg-7">
                    <div class="pool-content text-center wow fadeInUp" data-wow-delay="300ms">
                        <div class="section-heading text-center white">
                            <div class="line-"></div>
                            <h2>Infinity Pool</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris sceleri sque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris sceleri sque, at rutrum nulla dictum.</p>
                        </div>

                        <div class="row">
                            <div class="col-12 col-sm-4">
                                <div class="pool-feature">
                                    <i class="icon-cocktail-1"></i>
                                    <p>Pool Beachbar</p>
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="pool-feature">
                                    <i class="icon-swimming-pool"></i>
                                    <p>Infinity Pool</p>
                                </div>
                            </div>
                            <div class="col-12 col-sm-4">
                                <div class="pool-feature">
                                    <i class="icon-beach"></i>
                                    <p>Sunbeds</p>
                                </div>
                            </div>
                        </div>
                        <!-- Button -->
                        <a href="#" class="btn palatin-btn mt-50">Read More</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

HotelsReservation.WebUI/Views/Shared/Components/_ScriptComponentPartial/Default.cshtml
    <!-- ##### All Javascript Script ##### -->
    <!-- jQuery-2.2.4 js -->
    <script src="/palatin-gh-pages/js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="/palatin-gh-pages/js/bootstrap/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="/palatin-gh-pages/js/bootstrap/bootstrap.min.js"></script>
    <!-- All Plugins js -->
    <script src="/palatin-gh-pages/js/plugins/plugins.js"></script>
    <!-- Active js -->
    <script src="/palatin-gh-pages/js/active.js"></script>
       <script src="~/js/custom.js"></script>

HotelsReservation.WebUI/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>The Palatin - Hotel &amp; Resort Template</title>

    <!-- Favicon -->
    <link rel="icon" href="/palatin-gh-pages/img/core-img/favicon.ico">

    <!-- Core Stylesheet -->
    <link rel="stylesheet" href="/palatin-gh-pages/style.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/css/custom.css">

</head>

<body>
    <!-- Preloader -->
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="cssload-container">
            <div class="cssload-loading"><i></i><i></i><i></i><i></i></div>
        </div>
    </div>

    <!-- ##### Header Area Start ##### -->
    @await Component.InvokeAsync("_HeaderComponentPartial")
    <!-- ##### Header Area End ##### -->

        @RenderBody()  

 
    @await Component.InvokeAsync("_FooterComponentPartial")

    @await Component.InvokeAsync("_ScriptComponentPartial")

     @await RenderSectionAsync("Scripts", required: false)

</body>

</html>